- composer.lock
- database/seeders/AniDbResourceSeeder.php
Makes use of a REST API that itself uses manami-project's offline db.
> #45 feat(seed): create anidb anime resources

- composer.lock
- package-lock.json
- package.json
bumping dependencies to address potential security issue
> chore: dump dependencies

- app/JsonApi/QueryParser.php
- composer.lock
- package-lock.json
Addressing exceptions found in staging logs
> fix(api): adding missing checks for strictness of query string structure

- app/Concerns/JsonApi/PerformsResourceCollectionSearch.php
- app/Enums/JsonApi/PaginationStrategy.php
- app/Http/Controllers/Api/AnimeController.php
- app/Http/Controllers/Api/ArtistController.php
- app/Http/Controllers/Api/EntryController.php
- app/Http/Controllers/Api/SeriesController.php
- app/Http/Controllers/Api/SongController.php
- app/Http/Controllers/Api/SynonymController.php
- app/Http/Controllers/Api/ThemeController.php
- app/Http/Controllers/Api/VideoController.php
- app/Http/Resources/SearchResource.php
- app/Scout/Elastic/AnimeQueryPayload.php
- app/Scout/Elastic/ArtistQueryPayload.php
- app/Scout/Elastic/ElasticQueryPayload.php
- app/Scout/Elastic/EntryQueryPayload.php
- app/Scout/Elastic/SeriesQueryPayload.php
- app/Scout/Elastic/SongQueryPayload.php
- app/Scout/Elastic/SynonymQueryPayload.php
- app/Scout/Elastic/ThemeQueryPayload.php
- app/Scout/Elastic/VideoQueryPayload.php
- composer.lock
- package-lock.json
Incremental commit that adds search capabilities with JSON:API compliant pagination to existing index endpoints in the API. This also fixes constrained eager loads for searches. This does not fix top-level filtering which was removed by a breaking change in f21f41e3a65d77f6a77cc92d9902fe13ba3f8528.
> #127 feat(api): pagination strategies and constrained eager loads for search

- app/Console/Kernel.php
- composer.lock
- package-lock.json
* Schedules prune failed jobs command. I elected to leave the default behavior of running the command daily and pruning the last day's failed jobs.
* Bumped dependencies. The latest framework patch fixes a MySQL grammar error.
> #219 feat(queue): schedule pruned failed jobs command

- app/Http/Api/Filter/Billing/Transaction/TransactionExternalIdFilter.php
- app/Http/Controllers/Wiki/StreamableController.php
- app/Models/Billing/Balance.php
- app/Models/Billing/Transaction.php
- app/Nova/Resources/Billing/Transaction.php
- database/factories/Billing/TransactionFactory.php
- database/migrations/2021_05_13_192052_create_transactions_table.php
* Change external_id attribute to be nullable string to support UUIDs
* Chore: Reduce number of public functions
> #222 fix(transparency): change type for transaction external id column

- app/Concerns/Http/Resources/PerformsConstrainedEagerLoading.php
- app/Http/Api/Query.php
- app/Http/Resources/BaseCollection.php
- app/Http/Resources/BaseResource.php
- app/Http/Resources/SearchableCollection.php
- app/Http/Resources/Wiki/Resource/SearchResource.php
1. Fixes exception for search api resource inclusion.
2. Optimize global search resource to only query ES for selected fields.
> fix(api): address exceptions for resource inclusion in search endpoint & minimize requests

- app/Http/Resources/SearchableCollection.php
- composer.lock
- package-lock.json
- package.json
* Revert change to search endpoint resource inclusion
* Bump dependencies
> fix(api): revert search resource inclusion fix

- app/Enums/Models/Wiki/ResourceSite.php
- composer.lock
- config/sanctum.php
- database/seeders/AnimeResourceSeeder.php
- database/seeders/ArtistSeeder.php
- database/seeders/StudioSeeder.php
- database/seeders/WikiDeseeder.php
- package-lock.json
* Seed MAL studio resources when we seed MAL anime studios.
* Bump dependencies & update stubs
* Fix strict type error with ResourceSite::valueOf function.
* Add missing table to wiki deseeder script.
> fix(db): seed studio resources when seeding anime studios

- .github/CONTRIBUTING.md
- app/Nova/Resources/Billing/Balance.php
- app/Nova/Resources/Billing/Transaction.php
- resources/views/welcome.blade.php
- tests/Unit/Rules/Api/DistinctIgnoringDirectionTest.php
* fix a few links that were broken with the pages resource change
* add missing admin config for audit logs
* fixed a buggy test
* update some contributing.md instructions
> chore: fix links, missing admin config, buggy test

- composer.json
- composer.lock
- config/filesystems.php
- config/mail.php
- config/services.php
- package-lock.json
- package.json
trying to stay caught up with release days
Note: larastan 2.1 introduced a breaking change to the project due to the persistent config dependency binding another type to the config repository. For now I'm locking the version until I figure out whether to draft a PR or consider ditching the dependency.
> chore: update dependencies

- app/Http/Api/Field/EnumField.php
- app/Http/Api/Field/Wiki/Anime/Theme/Entry/EntryEpisodesField.php
- app/Http/Api/Field/Wiki/Anime/Theme/Entry/EntryNotesField.php
- app/Http/Api/Field/Wiki/Anime/Theme/Entry/EntryNsfwField.php
- app/Http/Api/Field/Wiki/Anime/Theme/Entry/EntrySpoilerField.php
- app/Http/Api/Field/Wiki/Anime/Theme/Entry/EntryThemeIdField.php
- app/Http/Api/Field/Wiki/Anime/Theme/Entry/EntryVersionField.php
- app/Http/Controllers/Api/Wiki/Anime/Theme/EntryController.php
- app/Http/Requests/Api/StoreRequest.php
- app/Http/Requests/Api/UpdateRequest.php
- app/Http/Requests/Api/Wiki/Anime/AnimeStoreRequest.php
- app/Http/Requests/Api/Wiki/Anime/Theme/Entry/EntryDestroyRequest.php
- app/Http/Requests/Api/Wiki/Anime/Theme/Entry/EntryForceDeleteRequest.php
- app/Http/Requests/Api/Wiki/Anime/Theme/Entry/EntryRestoreRequest.php
- app/Http/Requests/Api/Wiki/Anime/Theme/Entry/EntryStoreRequest.php
- app/Http/Requests/Api/Wiki/Anime/Theme/Entry/EntryUpdateRequest.php
- app/Http/Requests/Api/Wiki/Anime/Theme/ThemeStoreRequest.php
- app/Http/Requests/Api/Wiki/Anime/Theme/ThemeUpdateRequest.php
- app/Http/Requests/Api/Wiki/ExternalResource/ExternalResourceStoreRequest.php
- app/Http/Requests/Api/Wiki/ExternalResource/ExternalResourceUpdateRequest.php
- app/Http/Requests/Api/WriteRequest.php
- app/Models/Wiki/Anime/Theme/AnimeThemeEntry.php
- routes/api.php
- tests/Feature/Http/Api/Wiki/Anime/Theme/Entry/EntryDestroyTest.php
- tests/Feature/Http/Api/Wiki/Anime/Theme/Entry/EntryForceDeleteTest.php
- tests/Feature/Http/Api/Wiki/Anime/Theme/Entry/EntryRestoreTest.php
- tests/Feature/Http/Api/Wiki/Anime/Theme/Entry/EntryStoreTest.php
- tests/Feature/Http/Api/Wiki/Anime/Theme/Entry/EntryUpdateTest.php
Also did some cleanup to better encapsulate validation preparation
> feat(api): support extended write endpoints [incremental: entries]

- database/migrations/2022_04_09_234337_create_jobs_table.php
Add support for db queue connection. I want to see if the exception we're experiencing with queued jobs is caused by the connection type.
> feat: support db queue connection

- app/Http/Controllers/Wiki/VideoController.php
- tests/Feature/Http/Wiki/VideoTest.php
The proposed change will pass the video through nginx instead of using PHP.
> Update videos controller to serve videos through nginx

- app/Console/Kernel.php
- app/Contracts/Events/NovaNotificationEvent.php
- app/Events/Document/Page/PageDeleted.php
- app/Events/Wiki/Anime/AnimeDeleted.php
- app/Events/Wiki/Anime/Synonym/SynonymDeleted.php
- app/Events/Wiki/Anime/Theme/Entry/EntryDeleted.php
- app/Events/Wiki/Anime/Theme/ThemeDeleted.php
- app/Events/Wiki/Artist/ArtistDeleted.php
- app/Events/Wiki/ExternalResource/ExternalResourceDeleted.php
- app/Events/Wiki/Image/ImageDeleted.php
- app/Events/Wiki/Series/SeriesDeleted.php
- app/Events/Wiki/Song/SongDeleted.php
- app/Events/Wiki/Studio/StudioDeleted.php
- app/Events/Wiki/Video/VideoDeleted.php
- app/Listeners/NotifiesNovaUsers.php
- app/Models/BaseModel.php
- app/Pipes/Wiki/Anime/BackfillAnimePipe.php
- app/Services/Nova/NovaQueries.php
- tests/Unit/Events/NotifiesNovaUsersTest.php
* Configure model pruning. Soft-deleted models will be pruned after one week.
* Notify users with force deletion privileges of soft-deletions for review.
> Admin deletion notifications

- app/Console/Commands/Wiki/WikiDatabaseDumpCommand.php
- app/Events/Wiki/Audio/AudioCreated.php
- app/Events/Wiki/Audio/AudioDeleted.php
- app/Events/Wiki/Audio/AudioRestored.php
- app/Events/Wiki/Audio/AudioUpdated.php
- app/Models/Wiki/Audio.php
- app/Nova/Resources/Wiki/Audio.php
- app/Policies/Wiki/AudioPolicy.php
- database/factories/Wiki/AudioFactory.php
- database/migrations/2022_07_05_200425_create_audio_table.php
- database/seeders/PermissionSeeder.php
- resources/lang/en/nova.php
- tests/Feature/Events/Wiki/AudioTest.php
- tests/Feature/Jobs/Wiki/AudioTest.php
- tests/Unit/Models/Wiki/AudioTest.php
Initial commit for the audio model.
* Migration
* Model skeleton [attributes, factory, events]
* Nova Resource skeleton
* Policy for authorization with new permissions in db seeder
* Test Coverage
> feat: configure audio model [incremental]

- app/Http/Api/Field/Wiki/Audio/AudioBasenameField.php
- app/Http/Api/Field/Wiki/Audio/AudioFilenameField.php
- app/Http/Api/Field/Wiki/Audio/AudioMimeTypeField.php
- app/Http/Api/Field/Wiki/Audio/AudioPathField.php
- app/Http/Api/Field/Wiki/Audio/AudioSizeField.php
- app/Http/Api/Query/Wiki/Audio/AudioReadQuery.php
- app/Http/Api/Query/Wiki/Audio/AudioWriteQuery.php
- app/Http/Api/Schema/Wiki/AudioSchema.php
- app/Http/Controllers/Api/Wiki/AudioController.php
- app/Http/Requests/Api/Wiki/Audio/AudioDestroyRequest.php
- app/Http/Requests/Api/Wiki/Audio/AudioForceDeleteRequest.php
- app/Http/Requests/Api/Wiki/Audio/AudioIndexRequest.php
- app/Http/Requests/Api/Wiki/Audio/AudioRestoreRequest.php
- app/Http/Requests/Api/Wiki/Audio/AudioShowRequest.php
- app/Http/Requests/Api/Wiki/Audio/AudioStoreRequest.php
- app/Http/Requests/Api/Wiki/Audio/AudioUpdateRequest.php
- app/Http/Resources/Wiki/Collection/AudioCollection.php
- app/Http/Resources/Wiki/Resource/AudioResource.php
- tests/Feature/Http/Api/Wiki/Audio/AudioDestroyTest.php
- tests/Feature/Http/Api/Wiki/Audio/AudioForceDeleteTest.php
- tests/Feature/Http/Api/Wiki/Audio/AudioIndexTest.php
- tests/Feature/Http/Api/Wiki/Audio/AudioRestoreTest.php
- tests/Feature/Http/Api/Wiki/Audio/AudioShowTest.php
- tests/Feature/Http/Api/Wiki/Audio/AudioStoreTest.php
- tests/Feature/Http/Api/Wiki/Audio/AudioUpdateTest.php
Skeletal wiring for API endpoints + basic testing
> feat(api): add audio API endpoints [incremental]

- app/Nova/Lenses/BaseLens.php
- app/Nova/Resources/BaseResource.php
It's more annoying than helpful
> fix(admin): disable resource polling

- app/Http/Api/Schema/Wiki/AnimeSchema.php
- app/Models/Wiki/Anime.php
- app/Scout/Elasticsearch/Api/Schema/Wiki/AnimeSchema.php
add include path requested for animethemes-web
> feat(api): add audio include path to anime resource

- app/Concerns/Http/Requests/Api/ValidatesParameters.php
- app/Nova/Actions/Wiki/Anime/BackfillAnimeAction.php
- app/Nova/Actions/Wiki/Audio/MoveAudioAction.php
- app/Nova/Actions/Wiki/Studio/BackfillStudioAction.php
- app/Nova/Actions/Wiki/Video/MoveVideoAction.php
Addressing exceptions found in production app logs.
> fix(admin): model action query & fix(api): restricted type validation rules

- app/Actions/Storage/Base/DeleteAction.php
- app/Actions/Storage/Base/MoveAction.php
- app/Actions/Storage/Base/PruneAction.php
- app/Actions/Storage/Base/UploadAction.php
- app/Actions/Storage/Wiki/Video/UploadVideoAction.php
- app/Contracts/Actions/Storage/StorageAction.php
- app/Nova/Actions/Storage/StorageAction.php
- app/Nova/Actions/Storage/Wiki/Video/UploadVideoAction.php
- app/Rules/Wiki/Resource/ArtistResourceLinkFormatRule.php
- app/Rules/Wiki/Resource/StudioResourceLinkFormatRule.php
- tests/Feature/Actions/Storage/Admin/Dump/PruneDumpTest.php
- tests/Feature/Actions/Storage/Wiki/Audio/DeleteAudioTest.php
- tests/Feature/Actions/Storage/Wiki/Audio/MoveAudioTest.php
- tests/Feature/Actions/Storage/Wiki/Audio/UploadAudioTest.php
- tests/Feature/Actions/Storage/Wiki/Video/DeleteVideoTest.php
- tests/Feature/Actions/Storage/Wiki/Video/MoveVideoTest.php
- tests/Feature/Actions/Storage/Wiki/Video/UploadVideoTest.php
* Allow change requests for AniDB artist & studio resources (reported by Along)
* Attach entry to video if upload video action is run from entry detail screen (requested by Gap)
> feat(admin): support attaching entry when uploading video & fix(admin): support anidb change requests for artist & studio resources

- app/Providers/NovaServiceProvider.php
Forgot to prune this. Was raising exceptions in beta.
> fix(admin): remove user menu profile link

- app/Actions/Models/Wiki/Studio/Image/BackfillLargeCoverImageAction.php
- tests/Feature/Actions/Models/Wiki/Studio/Image/BackfillLargeCoverImageTest.php
Test applying higher priority fixes from main down to feature branch
> #490 fix(admin): update pattern for mal studio cover image (#492)

- app/Http/Api/Field/Billing/Balance/BalanceMonthToDateField.php
- app/Http/Api/Field/Billing/Balance/BalanceUsageField.php
- app/Http/Api/Field/Billing/Transaction/TransactionAmountField.php
- lang/en/validation.php
Keeping these changes separate so that they can be cherry-picked between branches easily.
> chore: applying framework updates

- app/Http/Kernel.php
- app/Http/Middleware/Models/RecordView.php
- app/Http/Middleware/Models/Wiki/RecordAudioView.php
- app/Http/Middleware/Models/Wiki/RecordVideoView.php
- routes/audio.php
- routes/video.php
Experimental change to test recording of views after the response is sent
> refactor: record views through terminable middleware after response is sent

- app/Actions/Storage/Base/UploadAction.php
- app/Actions/Storage/Wiki/Audio/UploadAudioAction.php
- app/Actions/Storage/Wiki/Video/Script/UploadScriptAction.php
- app/Actions/Storage/Wiki/Video/UploadVideoAction.php
- app/Models/Wiki/Video/VideoScript.php
Prefer eloquent upserts to repository reconciliation for upload actions to reduce number of queries / discord notification spam.
> refactor(admin): reduce number of queries for upload actions

- app/Actions/Fortify/CreateNewUser.php
- app/Actions/Fortify/UpdateUserProfileInformation.php
- app/Nova/Resources/Auth/User.php
- database/migrations/2023_01_21_042007_add_unique_user_name_constraint.php
At Mani's request to preempt client profiles
> feat(auth): add unique constraint to user name

- app/Http/Api/Field/List/Playlist/PlaylistViewCountField.php
- app/Http/Api/Schema/List/PlaylistSchema.php
- app/Http/Resources/List/Resource/PlaylistResource.php
- app/Models/List/Playlist.php
Did not add track count field yet since the key would conflict with the relation. Need to discuss this conflict.
> feat(api): adding playlist view count field

- app/Http/Api/Query/Auth/User/UserReadQuery.php
- app/Http/Controllers/Api/Auth/User/Me/MyController.php
- routes/api.php
- tests/Feature/Http/Api/Auth/User/Me/MyShowTest.php
Initial implementation of `/me` endpoint. I imagine this will need to change based on animethemes-web needs, but it exists for now.
> feat(api): add /me endpoint

- app/Http/Api/Field/Pivot/Wiki/AnimeSeries/AnimeSeriesAnimeIdField.php
- app/Http/Api/Field/Pivot/Wiki/AnimeSeries/AnimeSeriesSeriesIdField.php
- app/Http/Api/Schema/Pivot/Wiki/AnimeSeriesSchema.php
- app/Http/Controllers/Api/Pivot/Wiki/AnimeSeriesController.php
- app/Http/Resources/Pivot/Wiki/Collection/AnimeSeriesCollection.php
- app/Http/Resources/Pivot/Wiki/Resource/AnimeSeriesResource.php
- app/Pivots/Wiki/AnimeSeries.php
- routes/api.php
- tests/Feature/Http/Api/Pivot/Wiki/AnimeSeries/AnimeSeriesDestroyTest.php
- tests/Feature/Http/Api/Pivot/Wiki/AnimeSeries/AnimeSeriesIndexTest.php
- tests/Feature/Http/Api/Pivot/Wiki/AnimeSeries/AnimeSeriesShowTest.php
- tests/Feature/Http/Api/Pivot/Wiki/AnimeSeries/AnimeSeriesStoreTest.php
incremental commit for backfilling pivot resource endpoints
> feat(api): adding anime series pivot endpoints

- app/Actions/Http/Api/List/Playlist/Track/StoreTrackAction.php
- app/Http/Controllers/Api/List/Playlist/TrackController.php
- tests/Feature/Http/Api/List/Playlist/Track/TrackStoreTest.php
Incremental commit for managing doubly-linked list operations.
> feat(api): set first relation of playlist when creating initial track

- routes/api.php
> fix(api): resolve soft-deleted playlist for forward and backward index endpoints

- app/Actions/Models/List/Playlist/InsertTrackAction.php
- app/Http/Controllers/Api/List/Playlist/TrackController.php
> fix(api): fix insert track timeout

- app/Actions/Http/Api/List/Playlist/Track/StoreTrackAction.php
- app/Actions/Models/List/Playlist/InsertTrackAction.php
> adding logging for insert track action to investigate latency

- app/Actions/Models/List/Playlist/InsertTrackAction.php
- app/Http/Middleware/Models/RecordView.php
- app/Jobs/SendDiscordNotificationJob.php
- app/Listeners/SendDiscordNotification.php
- app/Notifications/DiscordNotification.php
Another attempt to address the job timeout issue
> fix(api): explicitly provide global scope for all defined feature checks

- app/Nova/Lenses/Anime/Resource/AnimeOfficialSiteResourceLens.php
- app/Nova/Lenses/Anime/Resource/AnimeTwitterResourceLens.php
- app/Nova/Lenses/Artist/Resource/ArtistAnimePlanetResourceLens.php
- app/Nova/Lenses/Artist/Resource/ArtistOfficialSiteResourceLens.php
- app/Nova/Lenses/Artist/Resource/ArtistTwitterResourceLens.php
- app/Nova/Resources/Wiki/Anime.php
- app/Nova/Resources/Wiki/Artist.php
Added Lenses:
* Anime Without Twitter Resource
* Anime Without Official Site Resource
* Artist Without Anime-Planet Resource
* Artist Without Twitter Resource
* Artist Without Official Site Resource
> feat: added more lenses

- app/Enums/Models/Wiki/ResourceSite.php
- app/Http/Api/Schema/Wiki/AnimeSchema.php
- app/Http/Api/Schema/Wiki/ArtistSchema.php
- app/Http/Api/Schema/Wiki/SongSchema.php
- database/seeders/Wiki/Anime/AnimeFormatAnilistSeeder.php
- database/seeders/Wiki/Anime/AnimeFormatMalSeeder.php
* Fixed song resource validation
* News paths in some schemas
* Splitting AnimeFormatSeeder into two classes
> feat: new included paths to song resources

- app/Enums/Auth/SpecialPermission.php
- app/Http/Api/Schema/Auth/RoleSchema.php
- app/Http/Api/Schema/Auth/User/MySchema.php
- app/Http/Api/Schema/Wiki/AnimeSchema.php
- app/Http/Api/Schema/Wiki/VideoSchema.php
- app/Models/Auth/User.php
- app/Models/Wiki/Video.php
- tests/Unit/Models/Wiki/VideoTest.php
* Added permissions as allowed include path.
* Added tracks and playlists as allowed include paths to videos
> feat: Added permission for revalidating pages

- app/Actions/Storage/Admin/Dump/DumpWikiAction.php
- app/Enums/Models/Wiki/ImageFacet.php
- app/Nova/Actions/Models/Wiki/AttachImageAction.php
- app/Nova/Actions/Models/Wiki/Image/AttachImageAction.php
- app/Nova/Resources/Wiki/Image.php
- app/Nova/Resources/Wiki/Studio.php
- database/seeders/Wiki/Image/MoveImageToAppropriateFolderSeeder.php
- lang/en/enums.php
* Added SongResource table dump;
* Added document, avatar & banner facets;
* Added Large Cover facet option to AttachStudioImageAction;
* Added upload image standalone action to grill & document facets.
> feat: added document, avatar & banner facets

- app/Actions/Models/Wiki/UploadImageAction.php
- app/Filament/Actions/Models/Wiki/Anime/BackfillAnimeAction.php
- app/Filament/HeaderActions/Models/Wiki/Anime/BackfillAnimeHeaderAction.php
- app/Filament/Resources/Wiki/Anime/Pages/EditAnime.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Filament/Resources/Wiki/Group.php
- app/Filament/Resources/Wiki/Group/Pages/CreateGroup.php
- app/Filament/Resources/Wiki/Group/Pages/EditGroup.php
- app/Filament/Resources/Wiki/Group/Pages/ListGroups.php
- app/Filament/Resources/Wiki/Group/Pages/ViewGroup.php
- app/Filament/Resources/Wiki/Group/RelationManagers/ThemeGroupRelationManager.php
- app/Filament/Resources/Wiki/Image.php
- app/Filament/TableActions/Models/Wiki/Image/UploadImageTableAction.php
- lang/en/filament.php
* Added group resource;
* Added group relation to theme resource;
* Removed old group field from theme resource;
* Added synonym type field;
* Added Backfill Synonyms Action;
* Added Upload Image Action.
> feat(filament): added group resource

- app/Concerns/Filament/HasTabs.php
- app/Filament/Components/Filters/DateFilter.php
- app/Filament/Components/Filters/NumberFilter.php
- app/Filament/Components/Filters/TextFilter.php
- app/Filament/Filters/DateFilter.php
- app/Filament/Resources/Auth/Role.php
- app/Filament/Resources/BaseResource.php
- app/Filament/Resources/Wiki/Anime.php
- app/Filament/Resources/Wiki/Anime/Synonym.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Filament/Resources/Wiki/Anime/Theme/Entry.php
- app/Filament/Resources/Wiki/Artist.php
- app/Filament/Resources/Wiki/Audio.php
- app/Filament/Resources/Wiki/ExternalResource.php
- app/Filament/Resources/Wiki/Group.php
- app/Filament/Resources/Wiki/Image.php
- app/Filament/Resources/Wiki/Series.php
- app/Filament/Resources/Wiki/Song.php
- app/Filament/Resources/Wiki/Studio.php
- app/Filament/Resources/Wiki/Video.php
- app/Filament/Tabs/BaseTab.php
- lang/en/filament.php
* Added filters;
* Added custom filters;
* Added shouldBeHidden method to tabs.
> feat(filament): added filters

- app/Filament/Components/Columns/TextColumn.php
- app/Filament/Components/Filters/TextFilter.php
- app/Filament/Components/Infolist/TextEntry.php
- app/Filament/Resources/Admin/Dump.php
- app/Filament/Resources/Document/Page.php
- app/Filament/Resources/Wiki/Anime.php
- app/Filament/Resources/Wiki/Anime/Theme/Entry.php
- app/Filament/Resources/Wiki/Artist.php
- app/Filament/Resources/Wiki/Audio.php
- app/Filament/Resources/Wiki/Group.php
- app/Filament/Resources/Wiki/Series.php
- app/Filament/Resources/Wiki/Studio.php
- app/Filament/Resources/Wiki/Video.php
- app/Filament/Resources/Wiki/Video/Script.php
- app/Models/Wiki/Anime/AnimeTheme.php
- lang/en/filament.php
- phpstan.neon
- tests/Unit/Models/Wiki/Video/ScriptTest.php
* Added more icons;
* Fixed trashed filter error;
* Fixed text filter nullable;
* Fixed theme field on entry edit page;
* Fixed slug rules;
* Fixed script has subtitle test;
* Prevent group from lazy load.
> fix(filament): fixed filter errors

- app/Filament/Resources/BaseRelationManager.php
- app/Filament/Resources/Wiki/Artist/RelationManagers/GroupArtistRelationManager.php
- app/Filament/Resources/Wiki/Artist/RelationManagers/MemberArtistRelationManager.php
- app/Filament/TableActions/BaseTableAction.php
- app/Filament/TableActions/Models/Wiki/Image/UploadImageTableAction.php
- app/Filament/TableActions/Repositories/ReconcileTableAction.php
- app/Filament/TableActions/Storage/StorageTableAction.php
- app/Http/Api/Schema/Admin/FeaturedThemeSchema.php
- app/Http/Api/Schema/List/Playlist/TrackSchema.php
- app/Models/Admin/FeaturedTheme.php
- lang/en/filament.php
* Added base table action;
* Added allowed included paths already documented;
* Fixed attach action;
* Fixed reconcile action;
* Fixed labels from artist relation managers.
> fix(filament): fixed attach action

- app/Actions/Discord/DiscordThreadAction.php
- app/Filament/Resources/Discord/DiscordThread.php
- app/Filament/Resources/Wiki/Video.php
- database/migrations/2024_05_31_052841_create_discord_threads_table.php
> fix(filament): fixed thread id as big integer

- app/Filament/Components/Columns/TextColumn.php
- app/Filament/Resources/Admin/Dump.php
- app/Filament/Resources/Base/BaseEditResource.php
- app/Filament/Resources/BaseResource.php
- app/Filament/Resources/Document/Page.php
- app/Filament/Resources/List/Playlist/Track.php
- app/Filament/Resources/Wiki/Anime.php
- app/Filament/Resources/Wiki/Anime/Synonym.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Filament/Resources/Wiki/Anime/Theme/Entry.php
- app/Filament/Resources/Wiki/Artist.php
- app/Filament/Resources/Wiki/ExternalResource.php
- app/Filament/Resources/Wiki/Group.php
- app/Filament/Resources/Wiki/Series.php
- app/Filament/Resources/Wiki/Song.php
- app/Filament/Resources/Wiki/Studio.php
- app/Filament/Resources/Wiki/Video.php
- app/Filament/Resources/Wiki/Video/Pages/EditVideo.php
- app/Policies/Admin/AnnouncementPolicy.php
- app/Policies/Admin/DumpPolicy.php
- app/Policies/Admin/FeaturePolicy.php
- app/Policies/Admin/FeaturedThemePolicy.php
* Added placeholders to `as` fields;
* Added missing `as` fields;
* Grouping delete actions;
* Fixed slug rules;
* Fixed filament policies.
> fix(filament): fixed actions policies

- app/Models/Discord/DiscordThread.php
- database/factories/Discord/DiscordThreadFactory.php
- database/migrations/2024_05_31_052841_create_discord_threads_table.php
- tests/Feature/Jobs/Discord/DiscordThreadTest.php
- tests/Unit/Models/Discord/DiscordThreadTest.php
* Added tests for DiscordThread model.
> refactor: changed thread pk type

- app/Actions/Discord/DiscordMessageAction.php
- app/Actions/Discord/DiscordThreadAction.php
- app/Discord/DiscordEmbed.php
- app/Discord/DiscordMessage.php
- app/Filament/Resources/Discord/DiscordThread.php
- app/Filament/TableActions/Models/Discord/DiscordEditMessageTableAction.php
- app/Filament/TableActions/Models/Discord/DiscordSendMessageTableAction.php
- lang/en/filament.php
* Added thread name automated.
> feat(filament): added discord message action

- app/Filament/Components/Infolist/TextEntry.php
- app/Filament/Resources/Document/Page.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Models/Document/Page.php
- lang/en/filament.php
* Added sections badges for page resource;
* Fixed hidden id column on list themes.
> feat(filament): artist schema on theme page

- app/Actions/Discord/DiscordVideoNotificationAction.php
- app/Filament/Actions/BaseAction.php
- app/Filament/BulkActions/Models/Wiki/Video/VideoDiscordNotificationBulkAction.php
- app/Filament/HeaderActions/BaseHeaderAction.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- lang/en/filament.php
* Added base modal width for base actions;
* Fixed artist action on theme form;
* Sort videos by on create discord notification.
> feat(filament): added should force thread option on create discord notification

- app/Concerns/Filament/Actions/HasPivotActionLogs.php
- app/Filament/Actions/Base/CreateAction.php
- app/Filament/Actions/Base/DetachAction.php
- app/Filament/Actions/Base/EditAction.php
- app/Filament/Actions/BaseAction.php
- app/Filament/HeaderActions/BaseHeaderAction.php
- app/Filament/RelationManagers/BaseRelationManager.php
- app/Filament/TableActions/BaseTableAction.php
- app/Models/Admin/ActionLog.php
* Fixed HasMany relation on pivot action log;
* Removed detach action from HasMany relation managers.
> feat(filament): added a refresh for relation managers after every action

- app/Filament/Resources/List/Playlist.php
- app/Filament/Resources/Wiki/Anime.php
- app/Http/Api/Schema/List/PlaylistSchema.php
> fix(api): added missing included paths for playlist

- README.md
- app/Actions/Models/Wiki/Anime/ApiAction/AnilistAnimeApiAction.php
- app/Actions/Models/Wiki/Anime/ApiAction/LivechartAnimeApiAction.php
- app/Actions/Models/Wiki/AttachResourceAction.php
- app/Enums/Models/Wiki/ResourceSite.php
- app/Filament/Actions/Models/Wiki/Anime/AttachAnimeResourceAction.php
- app/Filament/Actions/Models/Wiki/Anime/BackfillAnimeAction.php
- app/Filament/Actions/Models/Wiki/Artist/AttachArtistResourceAction.php
- app/Filament/HeaderActions/Models/Wiki/Anime/AttachAnimeResourceHeaderAction.php
- app/Filament/HeaderActions/Models/Wiki/Anime/BackfillAnimeHeaderAction.php
- app/Filament/HeaderActions/Models/Wiki/Artist/AttachArtistResourceHeaderAction.php
- app/Filament/Resources/Wiki/Anime/Pages/ListAnimes.php
- app/Filament/Resources/Wiki/Artist/Pages/ListArtists.php
- app/Filament/Tabs/Anime/Resource/AnimeXResourceTab.php
- app/Filament/Tabs/Artist/Resource/ArtistXResourceTab.php
- database/seeders/Wiki/ResourceAnimePlanetSeeder.php
- database/seeders/Wiki/ResourceTwitterXSeeder.php
- lang/en/enums.php
- lang/en/filament.php
- tests/Unit/Rules/Wiki/Resource/ResourceLinkFormatTest.php
* Migrated from Twitter to X Resources;
* Migrated from slug to IDs for Kitsu resources;
* Added seeder for get anime planet external ids.
> refactor: updating resources

- .env.example
- app/Http/Api/Schema/List/PlaylistSchema.php
> feat: added entry included path to playlist schema

- app/Filament/Actions/Base/CreateAction.php
- app/Filament/Actions/Models/Wiki/AttachImageAction.php
- app/Filament/HeaderActions/Models/Wiki/AttachImageHeaderAction.php
- app/Filament/Resources/Wiki/ExternalResource/Pages/ListExternalResources.php
- app/Filament/TableActions/Models/Wiki/Image/UploadImageTableAction.php
- lang/en/filament.php
* Added image crop aspect ratio for attach image action;
* Added helper text for attach images;
* Removed create option on resource table;
* Upload image action should be visible only on index page.
> fix: fixed some wiki stuff on filament

- app/Actions/Models/List/ExternalProfile/ExternalEntry/BaseExternalEntryTokenAction.php
- app/Actions/Models/List/ExternalProfile/ExternalEntry/Site/AnilistExternalEntryTokenAction.php
- app/Actions/Models/List/ExternalProfile/ExternalToken/Site/AnilistExternalTokenAction.php
- app/Actions/Models/List/ExternalProfile/StoreExternalProfileTokenAction.php
- app/Actions/Models/List/ExternalProfile/StoreExternalProfileUsernameAction.php
- app/Actions/Models/List/ExternalProfile/StoreExternalTokenAction.php
- app/Actions/Models/List/ExternalTokenCallbackAction.php
- app/Console/Kernel.php
- app/Events/List/ExternalProfile/ExternalToken/ExternalTokenCreated.php
- app/Events/List/ExternalProfile/ExternalToken/ExternalTokenDeleted.php
- app/Events/List/ExternalProfile/ExternalToken/ExternalTokenRestored.php
- app/Events/List/ExternalProfile/ExternalToken/ExternalTokenUpdated.php
- app/Http/Controllers/Api/List/External/ExternalTokenCallbackController.php
- app/Models/List/External/ExternalToken.php
- app/Models/List/ExternalProfile.php
- composer.json
- composer.lock
- database/factories/List/External/ExternalEntryFactory.php
- database/migrations/2022_09_29_203332_create_playlists_table.php
- database/migrations/2022_09_29_204718_create_playlist_tracks_table.php
- database/migrations/2024_08_26_022027_create_external_tokens_table.php
- tests/Unit/Models/Discord/DiscordThreadTest.php
- tests/Unit/Models/List/External/ExternalEntryTest.php
- tests/Unit/Models/List/External/ExternalTokenTest.php
- tests/Unit/Models/List/ExternalProfileTest.php
* Added external token callback action;
* Added unit tests for external lists;
* Added unique constrain to profile id on external token;
* Fixed AniList JWT decode;
* Fixed queries not being retrieved;
* Fixed external token events;
* Fixed token encryption;
* Changed tokens columns to long text.
> fix: fixed mostly stuff on external token callback

- app/Filament/Actions/Base/AttachAction.php
- app/Filament/Resources/Wiki/Artist.php
- app/Filament/Resources/Wiki/Song.php
- app/Http/Api/Field/Pivot/Wiki/ArtistMember/ArtistMemberAliasField.php
- app/Http/Api/Field/Pivot/Wiki/ArtistSong/ArtistSongAliasField.php
- app/Http/Api/Schema/Pivot/Wiki/ArtistMemberSchema.php
- app/Http/Api/Schema/Pivot/Wiki/ArtistSongSchema.php
- app/Models/Wiki/Artist.php
- app/Models/Wiki/Song.php
- app/Pivots/Wiki/ArtistMember.php
- app/Pivots/Wiki/ArtistSong.php
- composer.lock
- database/migrations/2024_10_03_062910_add_alias_attribute_to_artist_song_table.php
- lang/en/filament.php
> feat: added alias field to artist pivots

- app/Actions/Discord/DiscordThreadAction.php
- app/Actions/Discord/DiscordVideoNotificationAction.php
- app/Filament/Actions/Base/AttachAction.php
- app/Filament/Actions/Base/CreateAction.php
- app/Filament/Actions/Base/EditAction.php
- app/Filament/RelationManagers/BaseRelationManager.php
- app/Filament/RelationManagers/Wiki/ResourceRelationManager.php
- app/Filament/Resources/Wiki/Anime.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Filament/Resources/Wiki/Artist.php
- app/Filament/Resources/Wiki/Artist/RelationManagers/GroupArtistRelationManager.php
- app/Filament/Resources/Wiki/Artist/RelationManagers/MemberArtistRelationManager.php
- app/Filament/Resources/Wiki/Artist/RelationManagers/SongArtistRelationManager.php
- app/Filament/Resources/Wiki/ExternalResource.php
- app/Filament/Resources/Wiki/Song.php
- app/Filament/Resources/Wiki/Song/RelationManagers/ArtistSongRelationManager.php
- app/Filament/Resources/Wiki/Studio.php
- app/Pivots/Wiki/ArtistMember.php
- lang/en/filament.php
* Added missing alias field to theme modal;
* Changed discord actions stuff;
* Fixed some texts.
> refactor(filament): moved pivot fields to a proper function on relation managers

- app/Filament/Components/Filters/CheckboxFilter.php
- app/Filament/Resources/Auth/Role.php
- app/Filament/Resources/Wiki/Anime/Theme/Entry.php
- app/Filament/Resources/Wiki/Video.php
* Added missing video properties to video view page.
> fix(filament): added custom checkboxfilter class

- app/Concerns/Filament/Actions/Models/Wiki/Video/BackfillAudioActionTrait.php
- app/Concerns/Filament/Actions/Storage/Base/DeleteActionTrait.php
- app/Concerns/Filament/Actions/Storage/Base/MoveActionTrait.php
- app/Concerns/Filament/Actions/Storage/MoveAllActionTrait.php
- app/Filament/Actions/Storage/MoveAllAction.php
- app/Filament/HeaderActions/Storage/MoveAllHeaderAction.php
- app/Filament/Resources/Wiki/Video.php
- app/Filament/Resources/Wiki/Video/Pages/EditVideo.php
- app/Models/Wiki/Video.php
- app/Providers/AppServiceProvider.php
- composer.json
- composer.lock
- lang/en/filament.php
* Prohibit destructive commands when in production;
* Downgrade flysystem package version.
> feat(filament): added move all action

- app/Actions/Discord/DiscordThreadAction.php
- app/Events/BaseEvent.php
- app/Events/BasePivotEvent.php
- app/Filament/Resources/Discord/DiscordThread.php
* Removed trashed filter from thread index page.
> fix: attempt to fix no authenticated users in job context

- docker-compose.yml
- docker/8.4/Dockerfile
- docker/8.4/php.ini
- docker/8.4/start-container
- docker/8.4/supervisord.conf
* Ejected Sail configs to enable XDebug.
> chore: Updated Sail setup to use PHP 8.4

- app/Actions/Models/Wiki/BackfillAnimeAction.php
- app/Filament/Components/Fields/BelongsTo.php
- app/Filament/Components/Fields/Select.php
- app/Filament/Components/Filters/DateFilter.php
- app/Filament/Providers/GlobalSearchScoutProvider.php
- app/Filament/Resources/Admin/FeaturedTheme.php
- app/Filament/Resources/Base/BaseListResources.php
- app/Filament/Resources/BaseResource.php
- app/Filament/Resources/List/External/Pages/ListExternalProfiles.php
- app/Filament/Resources/List/Playlist/Pages/ListPlaylists.php
- app/Filament/Resources/Wiki/Anime/Pages/ListAnimes.php
- app/Filament/Resources/Wiki/Anime/Synonym/Pages/ListSynonyms.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Filament/Resources/Wiki/Anime/Theme/Entry.php
- app/Filament/Resources/Wiki/Anime/Theme/Entry/Pages/ListEntries.php
- app/Filament/Resources/Wiki/Anime/Theme/Pages/ListThemes.php
- app/Filament/Resources/Wiki/Artist/Pages/ListArtists.php
- app/Filament/Resources/Wiki/Series/Pages/ListSeries.php
- app/Filament/Resources/Wiki/Song/Pages/ListSongs.php
- app/Filament/Resources/Wiki/Song/Performance.php
- app/Filament/Resources/Wiki/Studio/Pages/ListStudios.php
- app/Filament/Resources/Wiki/Video/Pages/ListVideos.php
- app/Models/Wiki/Anime/Theme/AnimeThemeEntry.php
- lang/en/filament.php
* Added better labels for performance fields;
* Added default filter "without in" for themes;
* Added striped table;
* Added table defer loading;
* Escape reserved chars in the search query of Filament scout queries;
* Remove sort on search;
* Fixed duplicated synonyms when type is other;
* Fixed scout import entry model;
* Use non native date picker.
> feat: added better labels & fixed filament search

- app/Actions/Storage/Admin/Dump/DumpViewAction.php
- app/Actions/Storage/Admin/Dump/PruneDumpAction.php
- app/Actions/Storage/Base/PruneAction.php
- app/Console/Commands/Storage/Admin/ViewDumpCommand.php
- app/Console/Kernel.php
- app/Http/Middleware/Models/RecordView.php
- database/migrations/2024_12_10_142749_add_new_fields_to_views_table.php
* Admin dumps backup scheduled on mondays;
* Fixed views exception;
* Changed `views` columns to text type.
> feat: added views dump

- app/Actions/Models/List/ExternalProfile/StoreExternalProfileTokenAction.php
- app/Actions/Models/List/ExternalTokenCallbackAction.php
- app/Models/List/ExternalProfile.php
- elastic/migrations/2025_05_14_001128_create_profile_index.php
* Added profile elastic index;
* Fixed orphan token.
> fix: fixed duplicated tokens

- app/Actions/Models/List/ExternalProfile/StoreExternalProfileUsernameAction.php
- app/Actions/Models/List/ExternalProfile/SyncExternalProfileAction.php
- app/Actions/Models/List/ExternalTokenCallbackAction.php
- app/Console/Kernel.php
- app/Enums/Auth/SpecialPermission.php
- app/GraphQL/Directives/FeatureEnabledDirective.php
- app/GraphQL/Policies/BasePolicy.php
- app/Jobs/Middleware/ExternalProfileSiteRateLimited.php
- app/Models/Auth/User.php
- app/Policies/BasePolicy.php
* Added bypass authorization permission;
* Prohibits claimed profile from username action;
* Changed external site rate limiting values;
* Added some documentation.
> fix: attempt to fix dump reconciliation overlapping

- app/Actions/Storage/Wiki/Video/UploadVideoAction.php
- app/Filament/Actions/Storage/StorageAction.php
- composer.json
- composer.lock
> fix: fixed upload video action

- app/Actions/Models/Wiki/Song/ManageSongPerformances.php
- app/Filament/Actions/Base/DeleteAction.php
- app/Filament/Actions/Base/ForceDeleteAction.php
- app/Filament/Actions/Models/Discord/DiscordEditMessageAction.php
- app/Filament/Actions/Models/Discord/DiscordSendMessageAction.php
- app/Filament/Actions/Models/List/Playlist/FixPlaylistAction.php
- app/Filament/Actions/Repositories/Storage/ReconcileStorageAction.php
- app/Filament/Resources/Admin/ActionLog.php
- app/Filament/Resources/BaseResource.php
- app/Filament/Resources/List/ExternalProfile.php
- app/Filament/Resources/List/Playlist.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Filament/Resources/Wiki/Song/Performance/Pages/ListPerformances.php
- app/Filament/Resources/Wiki/Song/Performance/Schemas/PerformanceForm.php
- app/Filament/Resources/Wiki/Song/RelationManagers/PerformanceSongRelationManager.php
- lang/en/filament.php
* Fixed actions not appearing;
* Improve manage performances action;
* Action logs should not be manageable.
> feat: added the ability to delete tracks via panel

- app/Actions/Storage/Wiki/Video/UploadVideoAction.php
- app/Concerns/Filament/ActionLogs/HasActionLogs.php
- app/Filament/Actions/BaseAction.php
- app/Filament/Resources/Admin/ActionLog.php
- app/Models/Admin/ActionLog.php
- app/Rules/Wiki/Submission/SubmissionRule.php
- tests/Unit/Filament/BaseResourceTestCase.php
* Fixed ActionLog without model;
* Type Action explicitly;
* Display array values in fields.
> refactor: ffprobeData property of class

- app/GraphQL/Definition/Connection/EdgeConnection.php
- app/GraphQL/Definition/Mutations/Models/CreateMutation.php
- app/GraphQL/Definition/Mutations/Models/DeleteMutation.php
- app/GraphQL/Definition/Mutations/Models/List/ExternalProfile/SyncExternalProfileMutation.php
- app/GraphQL/Definition/Mutations/Models/UpdateMutation.php
- app/GraphQL/Resolvers/NodesResolver.php
- app/Providers/GraphQLServiceProvider.php
* Capitalize the first letter of the mutations.
> feat(graphql): overlap edge connection to allow a nodes field

- app/Actions/Models/Aggregate/SyncViewAggregatesAction.php
- app/Concerns/GraphQL/ResolvesAttributes.php
- app/GraphQL/Attributes/Deprecated.php
- app/GraphQL/Definition/Fields/Field.php
- app/GraphQL/Definition/Fields/Wiki/Audio/AudioViewsCountField.php
- app/GraphQL/Definition/Fields/Wiki/Video/VideoViewsCountField.php
* Using temporary table before syncing views.
> feat(graphql): mark viewsCount as deprecated

- app/Concerns/GraphQL/ResolvesArguments.php
- app/Enums/GraphQL/SortDirection.php
- app/GraphQL/Definition/Types/Auth/User/MeType.php
- app/GraphQL/Definition/Types/BaseType.php
- app/GraphQL/Definition/Types/Wiki/VideoType.php
- app/GraphQL/Directives/SortCustomDirective.php
- app/GraphQL/Support/Sort/RandomSort.php
- app/GraphQL/Support/Sort/Sort.php
- app/GraphQL/Support/SortableColumns.php
* Added video type belongs to audio type.
> refactor(graphql): sort class support

- app/Events/Wiki/Song/Membership/MembershipCreated.php
- app/Events/Wiki/Song/Membership/MembershipDeleted.php
- app/Events/Wiki/Song/Membership/MembershipDeleting.php
- app/Events/Wiki/Song/Membership/MembershipRestored.php
- app/Events/Wiki/Song/Membership/MembershipUpdated.php
- app/Events/Wiki/Song/Performance/PerformanceCreated.php
- app/Events/Wiki/Song/Performance/PerformanceDeleted.php
- app/Events/Wiki/Song/Performance/PerformanceDeleting.php
- app/Events/Wiki/Song/Performance/PerformanceRestored.php
- app/Events/Wiki/Song/Performance/PerformanceUpdated.php
- app/Filament/Components/Columns/BelongsToColumn.php
- app/Filament/Components/Infolist/BelongsToEntry.php
- app/Filament/Resources/Wiki/Anime/Theme.php
- app/Filament/Resources/Wiki/Song/Membership.php
- app/Filament/Resources/Wiki/Song/Performance.php
- app/GraphQL/Definition/Types/Wiki/Song/MembershipType.php
- app/Http/Api/Schema/Wiki/Song/MembershipSchema.php
- app/Models/Wiki/Song/Membership.php
- tests/Unit/Filament/Resources/Wiki/Song/MembershipTest.php
* Membership `artist` relation is now `group.`
> fix(filament): fixed belongs to entry

- app/GraphQL/Controllers/Wiki/Anime/FindAnimesByExternalSiteController.php
> fix(graphql): fixed find animes query site filter

- app/Enums/Models/Wiki/ThemeType.php
- app/GraphQL/Controllers/Wiki/Anime/AnimeYearsController.php
- app/GraphQL/Definition/Fields/Wiki/Anime/Theme/AnimeThemeTypeField.php
- app/GraphQL/Middleware/SetServingGraphQL.php
- app/GraphQL/Support/Argument/Argument.php
- app/GraphQL/Support/Directives/Filters/FilterDirective.php
- app/GraphQL/Support/Directives/Filters/InFilterDirective.php
- app/Models/Wiki/Anime/AnimeTheme.php
- config/lighthouse.php
* Added serving graphql middleware.
> feat(graphql): handle insert song

- app/Filament/Resources/Wiki/Song/Performance.php
- app/Filament/Tabs/Artist/Song/ArtistPerformanceTab.php
- app/GraphQL/Schema/Types/Wiki/ArtistType.php
- app/GraphQL/Support/Filter/EqFilter.php
- app/GraphQL/Support/Filter/GreaterFilter.php
- app/GraphQL/Support/Filter/InFilter.php
- app/GraphQL/Support/Filter/LesserFilter.php
- app/GraphQL/Support/Filter/LikeFilter.php
- app/GraphQL/Support/Filter/NotInFilter.php
- app/Models/Wiki/Artist.php
- app/Providers/GraphQLServiceProvider.php
- composer.json
- composer.lock
- config/graphql.php
* Disable complexity rule for localhost;
* Fix groupperformances relation for admin panel;
* Qualify columns on filters.
> feat: groupships
