AnimeThemes/animethemes-server

resources/js/app.js

The AniList GraphQL query was missing a parameter to define the media type returned. Sometimes anime got information from manga entries (often NSFW). This was fixed by explicitly setting `type: ANIME` in the query.

Design - Only fetch anime from AniList, not manga

---

.github/workflows/test.yml
README.md
composer.lock
database/seeders/AnimeResourceSeeder.php
database/seeders/AnimeSeasonSeeder.php
database/seeders/AnimeSeeder.php
database/seeders/AnimeThemeSeeder.php
database/seeders/ArtistCoverSeeder.php
database/seeders/ArtistSeeder.php
database/seeders/ArtistSongSeeder.php
database/seeders/SeriesSeeder.php
database/seeders/SynopsisCoverSeeder.php
database/seeders/VideoSeeder.php
database/seeders/VideoTagsSeeder.php
database/seeders/WikiPages.php
package-lock.json
tests/Feature/Http/Api/FallbackTest.php

Addressing a security item in php config prevented the seeders from retrieving external pages, so now we use a guzzle client. This also provides bridging changes needed in #152.

fix(seed): use guzzle client to retrieve contents of external pages

---

composer.lock
database/seeders/AniDbResourceSeeder.php
database/seeders/AnilistAnimeResourceSeeder.php
database/seeders/AnilistArtistResourceSeeder.php
database/seeders/AnimeResourceSeeder.php
database/seeders/AnimeSeasonSeeder.php
database/seeders/AnimeSeeder.php
database/seeders/AnimeThemeSeeder.php
database/seeders/ArtistCoverSeeder.php
database/seeders/ArtistSeeder.php
database/seeders/ArtistSongSeeder.php
database/seeders/KitsuResourceSeeder.php
database/seeders/SeriesSeeder.php
database/seeders/SynopsisCoverSeeder.php
database/seeders/VideoTagsSeeder.php
database/seeders/WikiPages.php

Addressing another issue found in staging log review: If one external service responds with an internal exception, the seeders raise an exception and abort execution altogether. This couples the uptime of each external service that we query, which is not desirable. Instead, we shall silently fail and move on to the next seeder.

fix(seed): fail silently if an external service raises an internal exception

---

app/Models/BaseModel.php
app/Models/User.php
composer.lock
package-lock.json

This is an incremental commit that fixes discord notifications for restored actions. We don't want to fire update events on restore as is the default behavior of the framework, so we override the soft delete trait to quietly save the restore changes without events.

#126 fix(discord): do not raise events on restore save operation

---

app/Http/Middleware/ThrottleRequestsWithService.php
phpstan.neon

Laravel won't use the valid named rate limiter if we don't pass exactly 3 arguments to the middleware handle method. If we have a valid named rate limiter, only pass in the needed arguments to the throttling middleware.

fix(redis): named rate limiters expect a specific number of arguments

---

app/JsonApi/QueryParser.php
composer.lock
package-lock.json
resources/markdown/community/requests.md
tests/Feature/Http/Api/Anime/AnimeIndexTest.php
tests/Feature/Http/Api/Anime/AnimeShowTest.php
tests/Feature/Http/Api/Anime/YearIndexTest.php
tests/Feature/Http/Api/Anime/YearShowTest.php
tests/Feature/Http/Api/Announcement/AnnouncementIndexTest.php
tests/Feature/Http/Api/Announcement/AnnouncementShowTest.php
tests/Feature/Http/Api/Artist/ArtistIndexTest.php
tests/Feature/Http/Api/Artist/ArtistShowTest.php
tests/Feature/Http/Api/Entry/EntryIndexTest.php
tests/Feature/Http/Api/Entry/EntryShowTest.php
tests/Feature/Http/Api/ExternalResource/ExternalResourceIndexTest.php
tests/Feature/Http/Api/ExternalResource/ExternalResourceShowTest.php
tests/Feature/Http/Api/Image/ImageIndexTest.php
tests/Feature/Http/Api/Image/ImageShowTest.php
tests/Feature/Http/Api/Series/SeriesIndexTest.php
tests/Feature/Http/Api/Series/SeriesShowTest.php
tests/Feature/Http/Api/Song/SongIndexTest.php
tests/Feature/Http/Api/Song/SongShowTest.php
tests/Feature/Http/Api/Synonym/SynonymIndexTest.php
tests/Feature/Http/Api/Synonym/SynonymShowTest.php
tests/Feature/Http/Api/Theme/ThemeIndexTest.php
tests/Feature/Http/Api/Theme/ThemeShowTest.php
tests/Feature/Http/Api/Video/VideoIndexTest.php
tests/Feature/Http/Api/Video/VideoShowTest.php
tests/Unit/JsonApi/QueryParserTest.php

Addressing deployment finding: API endpoints hydrate too many models. Previously, the resource inclusion strategy was to include all allowed paths by default. Now, the default is to exclude all allowed include paths, only returning the top-level models in the response.

#155 fix(api): changing resource inclusion strategy defaults

---

app/Concerns/Reconcile/Billing/ReconcilesBalance.php
app/Concerns/Reconcile/Billing/ReconcilesTransaction.php
app/Concerns/Reconcile/ReconcilesRepositories.php
app/Concerns/Reconcile/ReconcilesVideo.php
app/Console/Kernel.php
app/Enums/Filter/AllowedDateFormat.php
app/Http/Requests/TransparencyRequest.php
app/JsonApi/Filter/DateFilter.php
app/Models/Billing/Balance.php
app/Models/Billing/Transaction.php
app/Repositories/Service/Billing/DigitalOceanBalanceRepository.php
app/Repositories/Service/Billing/DigitalOceanTransactionRepository.php
app/Rules/Billing/TransparencyDateRule.php
tests/Feature/Console/Billing/BalanceReconcileTest.php
tests/Feature/Http/TransparencyTest.php
tests/Unit/JsonApi/Filter/DateFilterTest.php
tests/Unit/Rules/Billing/TransparencyDateTest.php

* Restoring the ordering of objects on the transparency page that was accidentally removed in the previous PR.
* Use arrow functions to define closures for set reconciliation operations rather  than performing the operation in the secondary trait.
* Adjust the time of day that we reconcile against DO so that the data isn't stale for almost 20 hours every day.
* Refactoring date format names.

fix(transparency): restore ordering & adjust reconcile job time, refactor: use lambdas in reconcile traits for comparison

---

app/Http/Api/Condition/WhereCondition.php

* The Elasticsearch driver expects a string for a term query value.
* Elasticsearch itself wants 'true' or 'false' strings for boolean fields.
We now coerce these filter values when building the search query.

fix(api): addressing strict type errors for top-level elasticsearch filter value

---

app/Http/Resources/SearchableCollection.php
app/Http/Resources/Wiki/Collection/AnimeCollection.php
app/Http/Resources/Wiki/Collection/ArtistCollection.php
app/Http/Resources/Wiki/Collection/EntryCollection.php
app/Http/Resources/Wiki/Collection/SeriesCollection.php
app/Http/Resources/Wiki/Collection/SongCollection.php
app/Http/Resources/Wiki/Collection/SynonymCollection.php
app/Http/Resources/Wiki/Collection/ThemeCollection.php
app/Http/Resources/Wiki/Collection/VideoCollection.php

Previously, we didn't support the `sort` query parameter for searches. This change adds that support. This shouldn't affect what matches are returned, but allows the user to order those matches if they want.
I refactored the trait into an abstract class that extends BaseCollection. The trait itself is only used by these subtypes and access static properties, so this better abides by the coding standards and is slightly more friendly in static analysis contexts.

fix(api): allow sorting on searches

---

app/Repositories/Service/DigitalOcean/VideoRepository.php

Addressing staging exception. Video reconciliation was broken. In fixing a psalm finding, a method call was replaced for discoverability, but did not return the data needed for reconciliation. For this process to work as expected, we need to make the assumption that the video disk uses the s3 driver.

fix(console): we have to assume that the video disk uses the s3 driver

---

app/Actions/Jetstream/RemoveTeamMember.php
app/Http/Api/Filter/Filter.php
app/Http/Controllers/Auth/RegisterController.php
app/Models/Auth/User.php
app/Policies/Wiki/AnimePolicy.php
app/Policies/Wiki/ArtistPolicy.php
app/Policies/Wiki/EntryPolicy.php
app/Policies/Wiki/ImagePolicy.php
app/Policies/Wiki/SeriesPolicy.php
app/Repositories/Service/DigitalOcean/Billing/DigitalOceanBalanceRepository.php
app/Repositories/Service/DigitalOcean/Billing/DigitalOceanTransactionRepository.php
app/Rules/Wiki/ResourceSiteDomainRule.php
database/seeders/AniDbResourceSeeder.php
database/seeders/AnilistAnimeResourceSeeder.php
database/seeders/AnilistArtistResourceSeeder.php
database/seeders/AnimeResourceSeeder.php
database/seeders/AnimeSeasonSeeder.php
database/seeders/AnimeThemeSeeder.php
database/seeders/ArtistCoverSeeder.php
database/seeders/ArtistSeeder.php
database/seeders/ArtistSongSeeder.php
database/seeders/KitsuResourceSeeder.php
database/seeders/MalSeasonYearSeeder.php
database/seeders/SeriesSeeder.php
database/seeders/SynopsisCoverSeeder.php
database/seeders/VideoTagsSeeder.php
database/seeders/WikiPages.php

* Minor fix to balance reconciliation for an error introduced when addressing psalm finding
* Prefer Http Facade to using guzzle client
* Reduce sleep time for seeders
* Address some PSR-12 compliance findings
* Reduce boolean return statements

chore: use http facade instead of guzzle client

---

app/Console/Commands/Wiki/DatabaseDumpCommand.php
app/Console/Commands/Wiki/PruneDatabaseDumpsCommand.php
app/Console/Kernel.php
config/filesystems.php
tests/Feature/Console/Commands/Wiki/DatabaseDumpTest.php
tests/Feature/Console/Commands/Wiki/PruneDatabaseDumpsTest.php

* Prune stale database dumps in a separate console command like the framework does for failed jobs, stale telescope entries, etc. By default, we are pruning database dumps more than 72 hours old. We can tweak this value in the future if needed.
* Database dumps are now contained in a configured filesystem. This was done primarily for testing, as faking a storage disk will give us a clean disk to perform tests. Parallel testing fails otherwise if we are writing to the actual disk as we were previously doing.

#162 feat(console): prune stale database dumps

---

app/Events/Wiki/Anime/AnimeCreated.php
app/Events/Wiki/Anime/AnimeDeleting.php
app/Events/Wiki/Anime/AnimeUpdated.php
app/Events/Wiki/Anime/Synonym/SynonymCreated.php
app/Events/Wiki/Anime/Synonym/SynonymDeleted.php
app/Events/Wiki/Anime/Synonym/SynonymRestored.php
app/Events/Wiki/Anime/Synonym/SynonymUpdated.php
app/Events/Wiki/Anime/Theme/ThemeCreated.php
app/Events/Wiki/Anime/Theme/ThemeDeleting.php
app/Events/Wiki/Anime/Theme/ThemeUpdated.php
app/Events/Wiki/Song/SongCreated.php
app/Events/Wiki/Song/SongDeleted.php
app/Events/Wiki/Song/SongDeleting.php
app/Events/Wiki/Song/SongRestored.php
app/Events/Wiki/Song/SongUpdated.php
app/Jobs/SendDiscordNotificationJob.php
app/Models/Wiki/Anime/AnimeSynonym.php
app/Models/Wiki/Song.php
app/Notifications/DiscordNotification.php
composer.lock
package-lock.json
tests/Feature/Jobs/SendDiscordNotificationTest.php

* Check feature flags before handling jobs or notifications. This is an attempt to address staging exceptions, and theoretically I think it's more sound to prevent handling of jobs and notifications as soon as the feature flag is toggled rather than letting queued jobs continue to be processed.
* Use relation constants for event eager loads.
* Bump dependencies.

fix(admin): check feature flags before handling jobs or notifications

---

app/Http/Controllers/Document/DocumentController.php
composer.lock
package-lock.json
tests/Feature/Events/Admin/AnnouncementTest.php
tests/Feature/Events/Auth/InvitationTest.php
tests/Feature/Events/Auth/UserTest.php
tests/Feature/Events/Billing/BalanceTest.php
tests/Feature/Events/Billing/TransactionTest.php
tests/Feature/Events/Wiki/Anime/SynonymTest.php
tests/Feature/Events/Wiki/Anime/Theme/EntryTest.php
tests/Feature/Events/Wiki/Anime/ThemeTest.php
tests/Feature/Events/Wiki/AnimeTest.php
tests/Feature/Events/Wiki/ArtistTest.php
tests/Feature/Events/Wiki/ExternalResourceTest.php
tests/Feature/Events/Wiki/ImageTest.php
tests/Feature/Events/Wiki/SeriesTest.php
tests/Feature/Events/Wiki/SongTest.php
tests/Feature/Events/Wiki/StudioTest.php
tests/Feature/Events/Wiki/VideoTest.php

Small addition to fill a gap in test coverage relating to the framework customization that suppresses the firing of updated events on restore.
Fixed a deprecation warning in commonmark.
Bumping dependencies.

test: restore quietly

---

app/Concerns/Http/Requests/Api/ValidatesConditionally.php
app/Concerns/Http/Requests/Api/ValidatesFields.php
app/Concerns/Http/Requests/Api/ValidatesFilters.php
app/Concerns/Http/Requests/Api/ValidatesIncludes.php
app/Concerns/Http/Requests/Api/ValidatesPaging.php
app/Concerns/Http/Requests/Api/ValidatesParameters.php
app/Concerns/Http/Requests/Api/ValidatesSorts.php
app/Http/Api/Criteria/Sort/FieldCriteria.php
app/Http/Api/Filter/TrashedFilter.php
app/Http/Api/Schema/Schema.php
app/Http/Requests/Api/BaseRequest.php
app/Http/Requests/Api/IndexRequest.php
app/Http/Requests/Api/ShowRequest.php
app/Http/Requests/Api/Wiki/Anime/YearIndexRequest.php
app/Http/Requests/Api/Wiki/SearchRequest.php

* Validates allowed types for every API endpoint.
* Refactor form requests to use a collection of traits to declutter.
* Fix issue where array was passed to delimited rule. Allowed values now bails on first failure and validates the type before we evaluate with Delimited.
* Fix ambiguous field sort by qualifying column.
Note: Has Filter is not fully supported, but from the logs it looks like no one is using the count feature, so this is getting pushed for now and support will be added next week.

feat(api): validate allowed filter types [incremental]

---

app/Http/Api/Field/Wiki/Artist/ArtistNameField.php
app/Http/Api/Field/Wiki/Artist/ArtistSlugField.php
app/Http/Controllers/Api/Wiki/ArtistController.php
app/Http/Requests/Api/Wiki/Artist/ArtistDestroyRequest.php
app/Http/Requests/Api/Wiki/Artist/ArtistForceDeleteRequest.php
app/Http/Requests/Api/Wiki/Artist/ArtistRestoreRequest.php
app/Http/Requests/Api/Wiki/Artist/ArtistStoreRequest.php
app/Http/Requests/Api/Wiki/Artist/ArtistUpdateRequest.php
composer.lock
package-lock.json
routes/api.php
tests/Feature/Http/Api/Wiki/Artist/ArtistDestroyTest.php
tests/Feature/Http/Api/Wiki/Artist/ArtistForceDeleteTest.php
tests/Feature/Http/Api/Wiki/Artist/ArtistRestoreTest.php
tests/Feature/Http/Api/Wiki/Artist/ArtistStoreTest.php
tests/Feature/Http/Api/Wiki/Artist/ArtistUpdateTest.php

Added extended CRUD API endpoints for artist resources.
Bumped dependencies.
Note: Github Actions are experiencing an outage at the time of writing. IMO this change is low risk.

feat(api): support extended write endpoints [incremental: artists]

---

app/Nova/Resources/Admin/Announcement.php
app/Nova/Resources/Auth/Invitation.php
app/Nova/Resources/Auth/User.php
app/Nova/Resources/Billing/Balance.php
app/Nova/Resources/Billing/Transaction.php
app/Nova/Resources/Document/Page.php
app/Nova/Resources/Wiki/Anime.php
app/Nova/Resources/Wiki/Anime/Synonym.php
app/Nova/Resources/Wiki/Anime/Theme.php
app/Nova/Resources/Wiki/Anime/Theme/Entry.php
app/Nova/Resources/Wiki/Artist.php
app/Nova/Resources/Wiki/ExternalResource.php
app/Nova/Resources/Wiki/Image.php
app/Nova/Resources/Wiki/Series.php
app/Nova/Resources/Wiki/Song.php
app/Nova/Resources/Wiki/Studio.php
app/Nova/Resources/Wiki/Video.php

* Explicitly declare searchable columns as columns to avoid column string being invoked as callable.
* Add missing Create Relation Buttons for BelongsToMany relations.
* Some QoL fixes to admin resources.
Note: v4.0.6 should be available tomorrow. This patch will fix the select issue.

fix(admin): explicitly declare searchable columns as columns

---

app/Nova/Actions/Wiki/Anime/BackfillAnimeAction.php
app/Nova/Resources/Admin/Announcement.php
app/Nova/Resources/Auth/Invitation.php
app/Nova/Resources/Auth/User.php
app/Nova/Resources/Billing/Balance.php
app/Nova/Resources/Billing/Transaction.php
app/Nova/Resources/Document/Page.php
app/Nova/Resources/Wiki/Anime.php
app/Nova/Resources/Wiki/Anime/Synonym.php
app/Nova/Resources/Wiki/Anime/Theme.php
app/Nova/Resources/Wiki/Anime/Theme/Entry.php
app/Nova/Resources/Wiki/Artist.php
app/Nova/Resources/Wiki/ExternalResource.php
app/Nova/Resources/Wiki/Image.php
app/Nova/Resources/Wiki/Series.php
app/Nova/Resources/Wiki/Song.php
app/Nova/Resources/Wiki/Studio.php
app/Nova/Resources/Wiki/Video.php
app/Pipes/Wiki/Anime/BackfillAnimeImage.php
app/Pipes/Wiki/Anime/BackfillAnimeResource.php

* Support backfilling multiple anime from index screen
* Fix Resource reconciliation to prevent duplicates from being created
* Allow all panels to be collapsible (introduced in v4.2.6)

feat(admin): allow backfilling multiple anime & fixing resource reconciliation

---

app/Concerns/Reconcile/ReconcilesRepositories.php
app/Console/Commands/Wiki/VideoReconcileCommand.php
app/Contracts/Repositories/Repository.php
app/Nova/Resources/Resource.php
app/Pipes/Wiki/Anime/Studio/BackfillAnimeStudios.php
app/Repositories/Eloquent/Billing/DigitalOceanBalanceRepository.php
app/Repositories/Eloquent/Billing/DigitalOceanTransactionRepository.php
app/Repositories/Eloquent/EloquentRepository.php
app/Repositories/Eloquent/Wiki/VideoRepository.php
app/Repositories/Service/DigitalOcean/Billing/DigitalOceanBalanceRepository.php
app/Repositories/Service/DigitalOcean/Billing/DigitalOceanTransactionRepository.php
app/Repositories/Service/DigitalOcean/VideoRepository.php
tests/Feature/Console/Commands/Billing/BalanceReconcileTest.php
tests/Feature/Console/Commands/Billing/TransactionReconcileTest.php
tests/Feature/Console/Commands/Wiki/VideoReconcileTest.php

* Video reconciliation now accepts a path option to reconcile s3 and the database against a single path. This way we don't have to hydrate 30k+ models to pick up one or two changes.
* Don't backfill anime studios if studio relation is already set.
* Bump search result count from 5 to 10 in nova.

feat(console): allow video reconciliation against a specific path

---

app/Enums/Models/Wiki/ResourceSite.php
tests/Unit/Enums/Models/Wiki/ResourceSiteTest.php

* Parse Anime-Planet ID when attaching or creating an Anime-Planet Anime Resource by scraping global JS object.
* Parse Kitsu ID when attaching or creating a Kitsu Anime Resource by querying API with slug.
* Use canonical Anime-Planet domain.

feat(admin): parse external id from sluggable anime resources

---

app/Concerns/Http/Requests/Api/ValidatesFilters.php
app/Http/Requests/Api/IndexRequest.php

Follow-up to yesterday's production log exception, closing another gap in API validation by validating null values for top-level parameters.

fix(api): validate null values for filter and sort parameters

---

app/Concerns/Http/Requests/Api/ValidatesFilters.php
app/Concerns/Http/Requests/Api/ValidatesParameters.php
app/Http/Api/Filter/BooleanFilter.php
app/Http/Api/Filter/DateFilter.php
app/Http/Api/Filter/EnumFilter.php
app/Http/Api/Filter/FloatFilter.php
app/Http/Api/Filter/HasFilter.php
app/Http/Api/Filter/IntFilter.php
app/Http/Api/Filter/StringFilter.php
app/Http/Requests/Api/IndexRequest.php
app/Rules/Api/DelimitedRule.php
app/Rules/Api/RandomSoleRule.php
composer.json
composer.lock
resources/lang/en/validation.php
tests/Unit/Rules/Api/DelimitedTest.php

Dropping spatie dependency since it filters out empty values without allowing us to override this behavior.
Since empty values raise a runtime exception for invalid include values, we are extracting their Delimited class to our own rule.

fix(api): validate untrimmed and empty values with custom delimited validation rule

---

app/Nova/Resources/Wiki/Anime.php
app/Nova/Resources/Wiki/Artist.php
app/Nova/Resources/Wiki/Studio.php

QoL update for new anime/artist/studio workflow. Rather than navigating away from the detail/index screen to attach a new resource, this can now be done inline or from the detail screen.

#487 feat(admin): attach resource from detail/inline

---

app/Concerns/Http/Requests/Api/ValidatesFilters.php
app/Enums/Http/Api/Filter/Clause.php
app/Enums/Http/Api/QualifyColumn.php
app/Http/Api/Criteria/Filter/WhereCriteria.php
app/Http/Api/Criteria/Filter/WhereInCriteria.php
app/Http/Api/Criteria/Sort/FieldCriteria.php
app/Http/Api/Field/AggregateField.php
app/Http/Api/Field/CountField.php
app/Http/Api/Field/Wiki/Video/VideoViewCountField.php
app/Http/Api/Filter/Filter.php
app/Http/Api/Query/Base/EloquentReadQuery.php
app/Http/Api/Schema/Wiki/VideoSchema.php
app/Http/Api/Sort/Sort.php
app/Http/Resources/BaseResource.php
app/Http/Resources/Wiki/Resource/VideoResource.php
app/Models/Wiki/Video.php

Initial support for aggregate fields. Includes sparse fieldset, sorting & filtering support. However, the video views field is excluded by default. It might be explicitly included.
Unfortunately this required a lot of optional parameters, sry.

feat(api): initial support for aggregate fields

---

app/Actions/Fortify/CreateNewUser.php
app/Providers/EventServiceProvider.php
config/fortify.php

Also fixing issue where verification email was not sent on registration. This isn't picked up on discovery, so the dispatcher wasn't aware of the listener. I chose to explicitly map this event to the listener and only discover app listeners.

feat(auth): enable fortify account registration

---

database/factories/Billing/BalanceFactory.php
database/factories/Billing/TransactionFactory.php
tests/Feature/Actions/Models/Wiki/Anime/Studio/BackfillAnimeStudiosTest.php

I didn't have much time today so I just fixed some brittle tests

test: fix value boundary in billing factories & backfill anime studios needs unique value from external api

---

app/Http/Api/Field/Wiki/Video/VideoTagsField.php

Fixes rendering issue for video tags field introduced in 0fc9fd8.

fix(api): video tags field should be formatted as string

---

app/Http/Api/Field/Pivot/Wiki/AnimeResource/AnimeResourceAnimeIdField.php
app/Http/Api/Field/Pivot/Wiki/AnimeResource/AnimeResourceAsField.php
app/Http/Api/Field/Pivot/Wiki/AnimeResource/AnimeResourceResourceIdField.php
app/Http/Api/Schema/Pivot/Wiki/AnimeResourceSchema.php
app/Http/Controllers/Api/Pivot/Wiki/AnimeResourceController.php
app/Http/Resources/Pivot/Wiki/Collection/AnimeResourceCollection.php
app/Http/Resources/Pivot/Wiki/Resource/AnimeResourceResource.php
app/Pivots/Wiki/AnimeResource.php
routes/api.php
tests/Feature/Http/Api/Pivot/Wiki/AnimeResource/AnimeResourceDestroyTest.php
tests/Feature/Http/Api/Pivot/Wiki/AnimeResource/AnimeResourceIndexTest.php
tests/Feature/Http/Api/Pivot/Wiki/AnimeResource/AnimeResourceShowTest.php
tests/Feature/Http/Api/Pivot/Wiki/AnimeResource/AnimeResourceStoreTest.php
tests/Feature/Http/Api/Pivot/Wiki/AnimeResource/AnimeResourceUpdateTest.php

* Testing new DX for adding new API endpoints, evaluating remaining pain points.
* We might need pivot resources configured to address some pain points in the transformation layer.
* There was a request for these actions in the API layer.
With this and AnimeImage being configured, there is a blueprint for pivots with and without pivot fields, so the rest can be backfilled fairly easily.

feat(api): adding crud endpoints for anime resource pivot type

---

app/Actions/Http/Api/List/Playlist/Track/StoreTrackAction.php
app/Actions/Http/Api/StoreAction.php
app/Actions/Models/List/Playlist/InsertTrackAction.php
app/Actions/Models/List/Playlist/InsertTrackAfterAction.php
app/Actions/Models/List/Playlist/InsertTrackBeforeAction.php
app/Http/Api/Field/List/Playlist/Track/TrackNextIdField.php
app/Http/Api/Field/List/Playlist/Track/TrackPreviousIdField.php
tests/Feature/Actions/Models/List/Playlist/InsertTrackAfterTest.php
tests/Feature/Actions/Models/List/Playlist/InsertTrackBeforeTest.php
tests/Feature/Actions/Models/List/Playlist/InsertTrackTest.php
tests/Feature/Http/Api/List/Playlist/Track/TrackStoreTest.php
tests/Feature/Http/Api/List/Playlist/Track/TrackUpdateTest.php

Adds doubly-linked list insert operations on track store action.
* By default, we append the new track to the end of the list.
* If `previous_id` is provided in the request, we will insert the new track **AFTER** the previous track.
* If `next_id` is provided in the request, we will insert the new track **BEFORE** the next track.
These parameters prohibit one another since it may make no sense to insert before and after the provided tracks.
Also added additional validation to anticipate update action where we check that we aren't trying to move a track before or after itself.

feat(api): add track store insert operations for doubly-linked list

---

app/Actions/Http/Api/List/Playlist/Track/RestoreTrackAction.php
app/Actions/Http/Api/RestoreAction.php
app/Http/Controllers/Api/List/Playlist/TrackController.php
tests/Feature/Http/Api/List/Playlist/Track/TrackRestoreTest.php

Inserts restored track to the end of the list.

feat(api): add track restore operations for doubly-linked list

---

app/Actions/Http/Api/List/Playlist/Track/StoreTrackAction.php
app/Jobs/Middleware/RateLimited.php
app/Listeners/SendDiscordNotification.php
composer.lock
config/queue.php

* Discord Message event listener should be handled synchronously and queue a job without blocking the hashids listener.
* Remove debug logging from store playlist track action.
* Bump dependencies.

fix(api): address queue lockout for store playlist track action

---

app/Actions/Discord/DiscordMessageAction.php
app/Actions/Discord/DiscordThreadAction.php
app/Actions/Discord/DiscordVideoNotificationAction.php
app/Discord/DiscordEmbed.php
app/Discord/DiscordMessage.php
app/Filament/TableActions/Models/Discord/DiscordEditMessageTableAction.php
app/Filament/TableActions/Models/Discord/DiscordSendMessageTableAction.php
lang/en/filament.php

* Added url regex validator;
* Changed from state updated to hint action;
* Changed field from markdown editor to rich editor;
* Changed from msg files to msg images;
* Default repeater items is now 0;
* Refactored discord message action;
* Using defined consts instead of loose strings;

feat(filament): URL hint action on discord message field

---

app/Filament/Actions/Models/Wiki/Anime/BackfillAnimeAction.php
app/Filament/Components/Columns/TextColumn.php
app/Filament/Components/Infolist/TextEntry.php
app/Filament/HeaderActions/Models/Wiki/Anime/BackfillAnimeHeaderAction.php
app/Filament/RelationManagers/BaseRelationManager.php
app/Filament/Resources/Base/BaseViewResource.php
app/Filament/Resources/BaseResource.php
app/Filament/Resources/Wiki/Anime/Theme/Entry/RelationManagers/VideoEntryRelationManager.php
tests/Feature/Http/Api/ThrottleTest.php

* Added actions on view page;
* Added forwarded ip tests;
* Fixed backfill synonyms action;
* Changed redirect rows from edit to view page;
* Changed default pagination page option from 5 to 10 on relation managers;

feat(filament): actions on view page

---

app/Enums/Models/List/ExternalProfileSite.php
app/Filament/Actions/Base/AttachAction.php
app/Filament/Actions/Base/CreateAction.php
app/Filament/Actions/Base/DetachAction.php
app/Http/Controllers/Api/Pivot/PivotController.php
app/Http/Middleware/LogRequest.php
app/Http/Middleware/Models/AuthorizesPivot.php
app/Policies/Auth/PermissionPolicy.php
app/Policies/Auth/RolePolicy.php
app/Policies/Auth/UserPolicy.php
app/Policies/BasePolicy.php
app/Policies/List/External/ExternalEntryPolicy.php
app/Policies/List/ExternalProfilePolicy.php
app/Policies/List/PlaylistPolicy.php
app/Policies/Wiki/Anime/AnimeThemePolicy.php
app/Policies/Wiki/Anime/Theme/AnimeThemeEntryPolicy.php
app/Policies/Wiki/AnimePolicy.php
app/Policies/Wiki/ArtistPolicy.php
app/Policies/Wiki/AudioPolicy.php
app/Policies/Wiki/ExternalResourcePolicy.php
app/Policies/Wiki/GroupPolicy.php
app/Policies/Wiki/ImagePolicy.php
app/Policies/Wiki/SeriesPolicy.php
app/Policies/Wiki/SongPolicy.php
app/Policies/Wiki/StudioPolicy.php
app/Policies/Wiki/VideoPolicy.php
routes/api.php
tests/Feature/Http/Api/Pivot/List/PlaylistImage/PlaylistImageStoreTest.php

Filament and API now use the same policies methods to validate pivot management. This way, the pivot validation is more customizable than just checking foreign and related policies.

feat: added new way to authorize pivots
